### ISSUE TITLE
Add collaborators to this repo

### ISSUE THREAD

**Issue by cody-carlson** [teradyne-dev-workshops/caption-this-1220#1]
## Comment below to be added as a collaborator

We will all be using this repository today. Even though it's public right now, you will not be able to make changes until you're given the correct permissions. We've automated this process via the GitHub API. Once you comment, we will add you as a collaborator.

You'll start to receive a lot of emails. (❗) You can slow these down immediately by clicking the **Unwatch** button at the top of the page and selecting either the **Participating and @mentions** or **Ignore** option.

**Comment by cody-carlson-learning** [comment]
hello I am excited for class!

**Comment by Carl-VT88** [comment]
This is the best dang repository ever!

**Comment by ejchung11** [comment]
hi!

**Comment by rogermow** [comment]
Nice and good day to all.

**Comment by VianeyVer** [comment]
This is a comment

**Comment by terkudok** [comment]
I joined git training class

**Comment by tanweechong1973** [comment]
Hello World!!!! Awesome!!!!

**Comment by yehjovi** [comment]
I'm joining git training class

**Comment by zhanjoh** [comment]
Hi

**Comment by kittybelling** [comment]
hello :)

**Comment by vtozarks** [comment]
Howdy!

**Comment by showjim** [comment]
Hello world

**Comment by ter-wangdavi** [comment]
Hi all
